name: Tarea
on:
  pull_request:

    types: [opened]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request }}
